import { promises as fs } from 'fs';
import path from 'path';
import { BaseEnvironmentPack } from '../EnvironmentPack';
import { EnvironmentPackDefinition } from '@core/types';

export class CppEnvironmentPack extends BaseEnvironmentPack {
  readonly definition: EnvironmentPackDefinition = {
    packId: 'codex-pack-cpp',
    displayName: 'C / C++',
    description: 'GCC, Clang, CMake, Make',
    category: 'systems',
    version: '1.0.0',
    dockerfile: 'Dockerfile',
    baseImageTag: 'codex-cpp:gcc14',
    defaultRuntimes: [
      { name: 'gcc', version: '14.2.0' },
      { name: 'clang', version: '18.1.0' },
      { name: 'cmake', version: '3.30.3' },
    ],
    defaultPackageManagers: [{ name: 'apt' }, { name: 'vcpkg' }],
    defaultCapabilities: ['filesystem', 'process', 'network'],
    buildCommand: 'cmake -B build && cmake --build build',
    testCommand: 'ctest --test-dir build',
    runCommand: './build/app',
    supportedProviderTypes: ['docker', 'wsl2', 'process'],
  };

  async scaffoldProject(targetDir: string, projectName: string): Promise<string[]> {
    await fs.mkdir(path.join(targetDir, 'src'), { recursive: true });
    await fs.mkdir(path.join(targetDir, 'tests'), { recursive: true });
    const created: string[] = [];

    const cmakeListsPath = path.join(targetDir, 'CMakeLists.txt');
    await fs.writeFile(
      cmakeListsPath,
      `cmake_minimum_required(VERSION 3.20)\nproject(${sanitizeIdent(projectName)} CXX)\n\nset(CMAKE_CXX_STANDARD 20)\nset(CMAKE_CXX_STANDARD_REQUIRED ON)\n\nadd_executable(app src/main.cpp)\n\nenable_testing()\nadd_executable(tests tests/test_main.cpp)\nadd_test(NAME basic_test COMMAND tests)\n`,
      'utf-8'
    );
    created.push(cmakeListsPath);

    const mainCppPath = path.join(targetDir, 'src', 'main.cpp');
    await fs.writeFile(
      mainCppPath,
      `#include <iostream>\n\nint main() {\n    std::cout << "Hello from ${projectName}, generated by CodeX Desktop." << std::endl;\n    return 0;\n}\n`,
      'utf-8'
    );
    created.push(mainCppPath);

    const testPath = path.join(targetDir, 'tests', 'test_main.cpp');
    await fs.writeFile(
      testPath,
      `#include <cassert>\n#include <iostream>\n\nint main() {\n    assert(2 + 2 == 4);\n    std::cout << "All tests passed." << std::endl;\n    return 0;\n}\n`,
      'utf-8'
    );
    created.push(testPath);

    return created;
  }
}

function sanitizeIdent(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, '_');
}
