import { promises as fs } from 'fs';
import path from 'path';
import { BaseEnvironmentPack } from '../EnvironmentPack';
import { EnvironmentPackDefinition } from '@core/types';

export class DotNetEnvironmentPack extends BaseEnvironmentPack {
  readonly definition: EnvironmentPackDefinition = {
    packId: 'codex-pack-dotnet',
    displayName: '.NET / C#',
    description: '.NET SDK, C#, NuGet',
    category: 'microsoft',
    version: '1.0.0',
    dockerfile: 'Dockerfile',
    baseImageTag: 'codex-dotnet:8.0',
    defaultRuntimes: [{ name: 'dotnet', version: '8.0.401' }],
    defaultPackageManagers: [{ name: 'nuget' }],
    defaultCapabilities: ['filesystem', 'process', 'network'],
    buildCommand: 'dotnet build',
    testCommand: 'dotnet test',
    runCommand: 'dotnet run',
    supportedProviderTypes: ['docker', 'wsl2', 'windows-sandbox', 'process'],
  };

  async scaffoldProject(targetDir: string, projectName: string): Promise<string[]> {
    const safeName = sanitizeIdent(projectName);
    await fs.mkdir(targetDir, { recursive: true });
    const created: string[] = [];

    const csprojPath = path.join(targetDir, `${safeName}.csproj`);
    await fs.writeFile(
      csprojPath,
      `<Project Sdk="Microsoft.NET.Sdk">\n\n  <PropertyGroup>\n    <OutputType>Exe</OutputType>\n    <TargetFramework>net8.0</TargetFramework>\n    <ImplicitUsings>enable</ImplicitUsings>\n    <Nullable>enable</Nullable>\n  </PropertyGroup>\n\n</Project>\n`,
      'utf-8'
    );
    created.push(csprojPath);

    const programCsPath = path.join(targetDir, 'Program.cs');
    await fs.writeFile(programCsPath, `Console.WriteLine("Hello from ${projectName}, generated by CodeX Desktop.");\n`, 'utf-8');
    created.push(programCsPath);

    await fs.mkdir(path.join(targetDir, `${safeName}.Tests`), { recursive: true });
    const testCsprojPath = path.join(targetDir, `${safeName}.Tests`, `${safeName}.Tests.csproj`);
    await fs.writeFile(
      testCsprojPath,
      `<Project Sdk="Microsoft.NET.Sdk">\n\n  <PropertyGroup>\n    <TargetFramework>net8.0</TargetFramework>\n    <IsPackable>false</IsPackable>\n  </PropertyGroup>\n\n  <ItemGroup>\n    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />\n    <PackageReference Include="xunit" Version="2.9.0" />\n    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />\n  </ItemGroup>\n\n</Project>\n`,
      'utf-8'
    );
    created.push(testCsprojPath);

    const testFilePath = path.join(targetDir, `${safeName}.Tests`, 'BasicTests.cs');
    await fs.writeFile(
      testFilePath,
      `using Xunit;\n\npublic class BasicTests\n{\n    [Fact]\n    public void SanityCheck()\n    {\n        Assert.Equal(4, 2 + 2);\n    }\n}\n`,
      'utf-8'
    );
    created.push(testFilePath);

    return created;
  }
}

function sanitizeIdent(name: string): string {
  return name.replace(/[^A-Za-z0-9_]/g, '_');
}
