import { promises as fs } from 'fs';
import path from 'path';
import { BaseEnvironmentPack } from '../EnvironmentPack';
import { EnvironmentPackDefinition } from '@core/types';

export class FlutterEnvironmentPack extends BaseEnvironmentPack {
  readonly definition: EnvironmentPackDefinition = {
    packId: 'codex-pack-flutter',
    displayName: 'Flutter',
    description: 'Flutter SDK, Dart, Android toolchain integration',
    category: 'mobile',
    version: '1.0.0',
    dockerfile: 'Dockerfile',
    baseImageTag: 'codex-flutter:3.24',
    defaultRuntimes: [
      { name: 'flutter', version: '3.24.3' },
      { name: 'dart', version: '3.5.3' },
    ],
    defaultPackageManagers: [{ name: 'pub' }],
    defaultCapabilities: ['filesystem', 'process', 'network', 'kvm'],
    buildCommand: 'flutter create --platforms=android --no-pub . && flutter build apk --debug',
    testCommand: 'flutter test',
    runCommand: 'flutter run',
    requiresHostVirtualization: true, // when targeting Android emulator; web/desktop targets do not require it
    supportedProviderTypes: ['docker', 'wsl2', 'process'],
  };

  async scaffoldProject(targetDir: string, projectName: string): Promise<string[]> {
    const safeName = sanitizePackageName(projectName);
    const created: string[] = [];

    await fs.mkdir(path.join(targetDir, 'lib'), { recursive: true });
    await fs.mkdir(path.join(targetDir, 'test'), { recursive: true });

    const pubspecPath = path.join(targetDir, 'pubspec.yaml');
    await fs.writeFile(
      pubspecPath,
      `name: ${safeName}\ndescription: A new Flutter project generated by CodeX Desktop.\npublish_to: 'none'\nversion: 1.0.0+1\n\nenvironment:\n  sdk: '>=3.5.0 <4.0.0'\n\ndependencies:\n  flutter:\n    sdk: flutter\n  cupertino_icons: ^1.0.8\n\ndev_dependencies:\n  flutter_test:\n    sdk: flutter\n  flutter_lints: ^4.0.0\n\nflutter:\n  uses-material-design: true\n`,
      'utf-8'
    );
    created.push(pubspecPath);

    const mainDartPath = path.join(targetDir, 'lib', 'main.dart');
    await fs.writeFile(
      mainDartPath,
      `import 'package:flutter/material.dart';\n\nvoid main() {\n  runApp(const MyApp());\n}\n\nclass MyApp extends StatelessWidget {\n  const MyApp({super.key});\n\n  @override\n  Widget build(BuildContext context) {\n    return MaterialApp(\n      title: '${projectName}',\n      home: Scaffold(\n        appBar: AppBar(title: const Text('${projectName}')),\n        body: const Center(\n          child: Text('Hello from ${projectName}, generated by CodeX Desktop.'),\n        ),\n      ),\n    );\n  }\n}\n`,
      'utf-8'
    );
    created.push(mainDartPath);

    const testPath = path.join(targetDir, 'test', 'widget_test.dart');
    await fs.writeFile(
      testPath,
      `import 'package:flutter/material.dart';\nimport 'package:flutter_test/flutter_test.dart';\nimport 'package:${safeName}/main.dart';\n\nvoid main() {\n  testWidgets('renders greeting text', (WidgetTester tester) async {\n    await tester.pumpWidget(const MyApp());\n    expect(find.textContaining('Hello from'), findsOneWidget);\n  });\n}\n`,
      'utf-8'
    );
    created.push(testPath);

    return created;
  }
}

function sanitizePackageName(name: string): string {
  const cleaned = name.toLowerCase().replace(/[^a-z0-9_]/g, '_');
  return /^[a-z]/.test(cleaned) ? cleaned : `app_${cleaned}`;
}
