import { promises as fs } from 'fs';
import path from 'path';
import { BaseEnvironmentPack } from '../EnvironmentPack';
import { EnvironmentPackDefinition } from '@core/types';

export class GoEnvironmentPack extends BaseEnvironmentPack {
  readonly definition: EnvironmentPackDefinition = {
    packId: 'codex-pack-go',
    displayName: 'Go',
    description: 'Go toolchain and modules',
    category: 'systems',
    version: '1.0.0',
    dockerfile: 'Dockerfile',
    baseImageTag: 'codex-go:1.23',
    defaultRuntimes: [{ name: 'go', version: '1.23.1' }],
    defaultPackageManagers: [{ name: 'go modules' }],
    defaultCapabilities: ['filesystem', 'process', 'network'],
    buildCommand: 'go build -o bin/app ./...',
    testCommand: 'go test ./...',
    runCommand: './bin/app',
    supportedProviderTypes: ['docker', 'wsl2', 'process'],
  };

  async scaffoldProject(targetDir: string, projectName: string): Promise<string[]> {
    const created: string[] = [];
    const moduleName = sanitizeModule(projectName);

    const goModPath = path.join(targetDir, 'go.mod');
    await fs.writeFile(goModPath, `module ${moduleName}\n\ngo 1.23\n`, 'utf-8');
    created.push(goModPath);

    const mainGoPath = path.join(targetDir, 'main.go');
    await fs.writeFile(
      mainGoPath,
      `package main\n\nimport "fmt"\n\nfunc main() {\n\tfmt.Println("Hello from ${projectName}, generated by CodeX Desktop.")\n}\n`,
      'utf-8'
    );
    created.push(mainGoPath);

    const testGoPath = path.join(targetDir, 'main_test.go');
    await fs.writeFile(
      testGoPath,
      `package main\n\nimport "testing"\n\nfunc TestSanity(t *testing.T) {\n\tif 2+2 != 4 {\n\t\tt.Fatal("math is broken")\n\t}\n}\n`,
      'utf-8'
    );
    created.push(testGoPath);

    return created;
  }
}

function sanitizeModule(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
}
