import { promises as fs } from 'fs';
import path from 'path';
import { BaseEnvironmentPack } from '../EnvironmentPack';
import { EnvironmentPackDefinition } from '@core/types';

export class JavaEnvironmentPack extends BaseEnvironmentPack {
  readonly definition: EnvironmentPackDefinition = {
    packId: 'codex-pack-java',
    displayName: 'Java / JVM',
    description: 'JDK, Gradle, Maven',
    category: 'jvm',
    version: '1.0.0',
    dockerfile: 'Dockerfile',
    baseImageTag: 'codex-java:21',
    defaultRuntimes: [{ name: 'jdk', version: '21.0.4' }],
    defaultPackageManagers: [{ name: 'gradle', version: '8.10' }, { name: 'maven', version: '3.9.9' }],
    defaultCapabilities: ['filesystem', 'process', 'network'],
    buildCommand: 'gradle build',
    testCommand: 'gradle test',
    runCommand: 'gradle run',
    supportedProviderTypes: ['docker', 'wsl2', 'process'],
  };

  async scaffoldProject(targetDir: string, projectName: string): Promise<string[]> {
    const pkg = 'com.codex.generated';
    const pkgPath = pkg.replace(/\./g, '/');
    await fs.mkdir(path.join(targetDir, 'src', 'main', 'java', pkgPath), { recursive: true });
    await fs.mkdir(path.join(targetDir, 'src', 'test', 'java', pkgPath), { recursive: true });
    const created: string[] = [];

    const buildGradlePath = path.join(targetDir, 'build.gradle');
    await fs.writeFile(
      buildGradlePath,
      `plugins {\n    id 'application'\n}\n\nrepositories {\n    mavenCentral()\n}\n\ndependencies {\n    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.0'\n}\n\napplication {\n    mainClass = '${pkg}.Main'\n}\n\ntest {\n    useJUnitPlatform()\n}\n`,
      'utf-8'
    );
    created.push(buildGradlePath);

    const settingsGradlePath = path.join(targetDir, 'settings.gradle');
    await fs.writeFile(settingsGradlePath, `rootProject.name = '${sanitizeIdent(projectName)}'\n`, 'utf-8');
    created.push(settingsGradlePath);

    const mainJavaPath = path.join(targetDir, 'src', 'main', 'java', pkgPath, 'Main.java');
    await fs.writeFile(
      mainJavaPath,
      `package ${pkg};\n\npublic class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello from ${projectName}, generated by CodeX Desktop.");\n    }\n}\n`,
      'utf-8'
    );
    created.push(mainJavaPath);

    const testJavaPath = path.join(targetDir, 'src', 'test', 'java', pkgPath, 'MainTest.java');
    await fs.writeFile(
      testJavaPath,
      `package ${pkg};\n\nimport org.junit.jupiter.api.Test;\nimport static org.junit.jupiter.api.Assertions.assertEquals;\n\nclass MainTest {\n    @Test\n    void sanity() {\n        assertEquals(4, 2 + 2);\n    }\n}\n`,
      'utf-8'
    );
    created.push(testJavaPath);

    return created;
  }
}

function sanitizeIdent(name: string): string {
  return name.replace(/[^A-Za-z0-9-]/g, '-');
}
