import { promises as fs } from 'fs';
import path from 'path';
import { BaseEnvironmentPack } from '../EnvironmentPack';
import { EnvironmentPackDefinition } from '@core/types';

export class NodeEnvironmentPack extends BaseEnvironmentPack {
  readonly definition: EnvironmentPackDefinition = {
    packId: 'codex-pack-node',
    displayName: 'Node.js / Web',
    description: 'Node.js, npm, pnpm, yarn, TypeScript, React, Next.js',
    category: 'web',
    version: '1.0.0',
    dockerfile: 'Dockerfile',
    baseImageTag: 'codex-node:20',
    defaultRuntimes: [
      { name: 'node', version: '20.17.0' },
      { name: 'typescript', version: '5.6.2' },
    ],
    defaultPackageManagers: [{ name: 'npm', version: '10.8.2' }, { name: 'pnpm' }, { name: 'yarn' }],
    defaultCapabilities: ['filesystem', 'process', 'network'],
    buildCommand: 'npm run build',
    testCommand: 'npm test',
    runCommand: 'npm start',
    supportedProviderTypes: ['docker', 'wsl2', 'process'],
  };

  async scaffoldProject(targetDir: string, projectName: string): Promise<string[]> {
    await fs.mkdir(path.join(targetDir, 'src'), { recursive: true });
    const created: string[] = [];

    const packageJson = {
      name: projectName,
      version: '0.1.0',
      private: true,
      scripts: {
        build: 'tsc -p tsconfig.json',
        start: 'node dist/index.js',
        test: 'node --test dist/**/*.test.js',
      },
      devDependencies: { typescript: '^5.6.2', '@types/node': '^22.7.4' },
    };
    const packageJsonPath = path.join(targetDir, 'package.json');
    await fs.writeFile(packageJsonPath, JSON.stringify(packageJson, null, 2), 'utf-8');
    created.push(packageJsonPath);

    const tsconfig = {
      compilerOptions: {
        target: 'ES2022',
        module: 'commonjs',
        outDir: 'dist',
        rootDir: 'src',
        strict: true,
        esModuleInterop: true,
      },
      include: ['src/**/*.ts'],
    };
    const tsconfigPath = path.join(targetDir, 'tsconfig.json');
    await fs.writeFile(tsconfigPath, JSON.stringify(tsconfig, null, 2), 'utf-8');
    created.push(tsconfigPath);

    const indexTsPath = path.join(targetDir, 'src', 'index.ts');
    await fs.writeFile(
      indexTsPath,
      `console.log("Hello from ${projectName}, generated by CodeX Desktop.");\n`,
      'utf-8'
    );
    created.push(indexTsPath);

    return created;
  }
}
