import { promises as fs } from 'fs';
import path from 'path';
import { BaseEnvironmentPack } from '../EnvironmentPack';
import { EnvironmentPackDefinition } from '@core/types';

export class PythonEnvironmentPack extends BaseEnvironmentPack {
  readonly definition: EnvironmentPackDefinition = {
    packId: 'codex-pack-python',
    displayName: 'Python',
    description: 'Python, pip, venv, FastAPI, Django',
    category: 'python',
    version: '1.0.0',
    dockerfile: 'Dockerfile',
    baseImageTag: 'codex-python:3.12',
    defaultRuntimes: [{ name: 'python', version: '3.12.6' }],
    defaultPackageManagers: [{ name: 'pip', version: '24.2' }],
    defaultCapabilities: ['filesystem', 'process', 'network'],
    buildCommand: 'pip install -r requirements.txt',
    testCommand: 'python -m pytest',
    runCommand: 'python src/main.py',
    supportedProviderTypes: ['docker', 'wsl2', 'process'],
  };

  async scaffoldProject(targetDir: string, projectName: string): Promise<string[]> {
    await fs.mkdir(path.join(targetDir, 'src'), { recursive: true });
    await fs.mkdir(path.join(targetDir, 'tests'), { recursive: true });
    const created: string[] = [];

    const mainPath = path.join(targetDir, 'src', 'main.py');
    await fs.writeFile(mainPath, `def main() -> None:\n    print("Hello from ${projectName}, generated by CodeX Desktop.")\n\n\nif __name__ == "__main__":\n    main()\n`, 'utf-8');
    created.push(mainPath);

    const testPath = path.join(targetDir, 'tests', 'test_main.py');
    await fs.writeFile(
      testPath,
      `import sys\nimport os\n\nsys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))\n\nfrom main import main  # noqa: E402\n\n\ndef test_main_runs(capsys):\n    main()\n    captured = capsys.readouterr()\n    assert "Hello" in captured.out\n`,
      'utf-8'
    );
    created.push(testPath);

    const requirementsPath = path.join(targetDir, 'requirements.txt');
    await fs.writeFile(requirementsPath, 'pytest>=8.0.0\n', 'utf-8');
    created.push(requirementsPath);

    return created;
  }
}
