import { promises as fs } from 'fs';
import path from 'path';
import { BaseEnvironmentPack } from '../EnvironmentPack';
import { EnvironmentPackDefinition } from '@core/types';

export class ReactNativeEnvironmentPack extends BaseEnvironmentPack {
  readonly definition: EnvironmentPackDefinition = {
    packId: 'codex-pack-react-native',
    displayName: 'React Native',
    description: 'React Native, Metro bundler, and Android toolchain integration',
    category: 'mobile',
    version: '1.0.0',
    dockerfile: 'Dockerfile',
    baseImageTag: 'codex-react-native:node20',
    defaultRuntimes: [{ name: 'node', version: '20.17.0' }, { name: 'react-native', version: '0.75.3' }],
    defaultPackageManagers: [{ name: 'npm' }, { name: 'yarn' }],
    defaultCapabilities: ['filesystem', 'process', 'network', 'kvm'],
    buildCommand: 'gradle -p android assembleDebug',
    testCommand: 'npx jest',
    runCommand: 'npx react-native run-android',
    requiresHostVirtualization: true,
    supportedProviderTypes: ['docker', 'wsl2', 'process'],
  };

  async scaffoldProject(targetDir: string, projectName: string): Promise<string[]> {
    const safeName = sanitizeIdent(projectName) || 'codexapp';
    const created: string[] = [];
    const javaDir = path.join(targetDir, 'android', 'app', 'src', 'main', 'java', 'com', 'codex', 'app');
    await fs.mkdir(path.join(targetDir, '__tests__'), { recursive: true });
    await fs.mkdir(javaDir, { recursive: true });
    await fs.mkdir(path.join(targetDir, 'android', 'app', 'src', 'main'), { recursive: true });
    await fs.mkdir(path.join(targetDir, 'android', 'gradle', 'wrapper'), { recursive: true });

    const files: Record<string, string> = {
      'package.json': JSON.stringify({
        name: safeName, version: '0.0.1', private: true,
        scripts: { android: 'react-native run-android', start: 'react-native start', test: 'jest' },
        dependencies: { react: '18.3.1', 'react-native': '0.75.3' },
        devDependencies: { '@babel/core': '^7.25.2', '@react-native/babel-preset': '0.75.3', jest: '^29.7.0', 'react-test-renderer': '18.3.1' },
      }, null, 2),
      'app.json': JSON.stringify({ name: safeName, displayName: projectName }, null, 2),
      'babel.config.js': "module.exports = { presets: ['module:@react-native/babel-preset'] };\n",
      'index.js': `import { AppRegistry } from 'react-native';\nimport App from './App';\nimport { name as appName } from './app.json';\nAppRegistry.registerComponent(appName, () => App);\n`,
      'App.tsx': `import React from 'react';\nimport { SafeAreaView, Text } from 'react-native';\nexport default function App(): React.JSX.Element { return <SafeAreaView><Text>Hello from ${escapeJs(projectName)}, generated by CodeX Desktop.</Text></SafeAreaView>; }\n`,
      '__tests__/App.test.tsx': `import React from 'react';\nimport renderer from 'react-test-renderer';\nimport App from '../App';\ntest('renders correctly', () => { renderer.create(<App />); });\n`,
      'android/settings.gradle': `pluginManagement { includeBuild('../node_modules/@react-native/gradle-plugin'); repositories { google(); mavenCentral(); gradlePluginPortal() } }\ndependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { google(); mavenCentral() } }\nplugins { id 'com.facebook.react.settings' }\nrootProject.name = '${safeName}'\ninclude ':app'\nincludeBuild('../node_modules/@react-native/gradle-plugin')\n`,
      'android/build.gradle': `plugins { id 'com.android.application' version '8.5.2' apply false; id 'com.facebook.react' version '0.75.3' apply false }\n`,
      'android/gradle.properties': 'android.useAndroidX=true\nhermesEnabled=true\n',
      'android/app/build.gradle': `plugins { id 'com.android.application'; id 'com.facebook.react' }\nreact { autolinkLibrariesWithApp() }\nandroid { namespace 'com.codex.app'; compileSdk 34; defaultConfig { applicationId 'com.codex.app'; minSdk 24; targetSdk 34; versionCode 1; versionName '1.0' } }\ndependencies { implementation 'com.facebook.react:react-android' }\n`,
      'android/app/src/main/AndroidManifest.xml': `<manifest xmlns:android="http://schemas.android.com/apk/res/android"><application android:label="${escapeXml(projectName)}" android:name=".MainApplication"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity></application></manifest>`,
      'android/app/src/main/java/com/codex/app/MainActivity.java': `package com.codex.app;\nimport com.facebook.react.ReactActivity;\npublic class MainActivity extends ReactActivity { @Override protected String getMainComponentName() { return "${safeName}"; } }\n`,
      'android/app/src/main/java/com/codex/app/MainApplication.java': `package com.codex.app;\nimport android.app.Application;\nimport com.facebook.react.ReactApplication;\nimport com.facebook.react.ReactNativeHost;\nimport com.facebook.react.defaults.DefaultReactNativeHost;\nimport com.facebook.soloader.SoLoader;\npublic class MainApplication extends Application implements ReactApplication { private final ReactNativeHost host = new DefaultReactNativeHost(this) { @Override public boolean getUseDeveloperSupport(){ return BuildConfig.DEBUG; } @Override protected String getJSMainModuleName(){ return "index"; } }; @Override public ReactNativeHost getReactNativeHost(){ return host; } @Override public void onCreate(){ super.onCreate(); SoLoader.init(this, false); } }\n`,
      'android/gradle/wrapper/gradle-wrapper.properties': 'distributionBase=GRADLE_USER_HOME\ndistributionPath=wrapper/dists\nzipStoreBase=GRADLE_USER_HOME\nzipStorePath=wrapper/dists\ndistributionUrl=https\\://services.gradle.org/distributions/gradle-8.7-bin.zip\n',
    };
    for (const [rel, content] of Object.entries(files)) {
      const file = path.join(targetDir, rel); await fs.mkdir(path.dirname(file), { recursive: true }); await fs.writeFile(file, content, 'utf-8'); created.push(file);
    }
    const gradlew = path.join(targetDir, 'android', 'gradlew');
    await fs.writeFile(gradlew, '#!/bin/sh\nset -eu\nif command -v gradle >/dev/null 2>&1; then exec gradle "$@"; fi\nV=8.7; B="$HOME/.gradle/codex-wrapper/$V"; if [ ! -x "$B/gradle-$V/bin/gradle" ]; then mkdir -p "$B"; curl -fsSL "https://services.gradle.org/distributions/gradle-$V-bin.zip" -o "$B/gradle.zip"; unzip -q -o "$B/gradle.zip" -d "$B"; rm -f "$B/gradle.zip"; fi; exec "$B/gradle-$V/bin/gradle" "$@"\n', 'utf-8');
    await fs.chmod(gradlew, 0o755); created.push(gradlew);
    const gradlewBat = path.join(targetDir, 'android', 'gradlew.bat');
    await fs.writeFile(gradlewBat, '@echo off\nwhere gradle >nul 2>nul\nif %ERRORLEVEL% EQU 0 ( gradle %* & exit /b %ERRORLEVEL% )\nset "V=8.7"\nset "B=%USERPROFILE%\\.gradle\\codex-wrapper\\%V%"\nif not exist "%B%\\gradle-%V%\\bin\\gradle.bat" powershell -NoProfile -Command "New-Item -ItemType Directory -Force -Path \'%B%\' | Out-Null; Invoke-WebRequest -UseBasicParsing -Uri \'https://services.gradle.org/distributions/gradle-%V%-bin.zip\' -OutFile \'%B%\\gradle.zip\'; Expand-Archive -Force \'%B%\\gradle.zip\' \'%B%\'; Remove-Item \'%B%\\gradle.zip\'"\ncall "%B%\\gradle-%V%\\bin\\gradle.bat" %*\n', 'utf-8'); created.push(gradlewBat);
    return created;
  }
}
function sanitizeIdent(name: string): string { return name.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^[^a-z]+/, '') || 'codexapp'; }
function escapeXml(value: string): string { return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
function escapeJs(value: string): string { return value.replace(/[`\\$]/g, '\\$&').replace(/'/g, "\\'"); }
