import { promises as fs } from 'fs';
import path from 'path';
import { BaseEnvironmentPack } from '../EnvironmentPack';
import { EnvironmentPackDefinition } from '@core/types';

export class RustEnvironmentPack extends BaseEnvironmentPack {
  readonly definition: EnvironmentPackDefinition = {
    packId: 'codex-pack-rust',
    displayName: 'Rust',
    description: 'Rust toolchain via rustup, cargo',
    category: 'systems',
    version: '1.0.0',
    dockerfile: 'Dockerfile',
    baseImageTag: 'codex-rust:1.81',
    defaultRuntimes: [{ name: 'rust', version: '1.81.0' }],
    defaultPackageManagers: [{ name: 'cargo', version: '1.81.0' }],
    defaultCapabilities: ['filesystem', 'process', 'network'],
    buildCommand: 'cargo build --release',
    testCommand: 'cargo test',
    runCommand: 'cargo run',
    supportedProviderTypes: ['docker', 'wsl2', 'process'],
  };

  async scaffoldProject(targetDir: string, projectName: string): Promise<string[]> {
    await fs.mkdir(path.join(targetDir, 'src'), { recursive: true });
    const created: string[] = [];

    const cargoToml = `[package]\nname = "${sanitizeCrateName(projectName)}"\nversion = "0.1.0"\nedition = "2021"\n\n[dependencies]\n`;
    const cargoTomlPath = path.join(targetDir, 'Cargo.toml');
    await fs.writeFile(cargoTomlPath, cargoToml, 'utf-8');
    created.push(cargoTomlPath);

    const mainRsPath = path.join(targetDir, 'src', 'main.rs');
    await fs.writeFile(mainRsPath, `fn main() {\n    println!("Hello from ${projectName}, generated by CodeX Desktop.");\n}\n\n#[cfg(test)]\nmod tests {\n    #[test]\n    fn it_works() {\n        assert_eq!(2 + 2, 4);\n    }\n}\n`, 'utf-8');
    created.push(mainRsPath);

    return created;
  }
}

function sanitizeCrateName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9_-]/g, '-');
}
